name: Build Nesting App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Developer Command Prompt for VS
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build C++ DLL
      run: cl.exe /LD NestingCore.cpp /Fe:NestingEngine.dll

    - name: Publish C# App
      run: dotnet publish NestingApp.csproj -c Release -o ./ReadyApp

    - name: Add DLL to App Folder
      run: Copy-Item -Path NestingEngine.dll -Destination ./ReadyApp/

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MyNestingProgram
        path: ./ReadyApp/
